### ISSUE TITLE
Jake Steiner isn't the best guy to support

### ISSUE THREAD

**Issue by nottnottloop** [denisk20/diopter-calc#8]
Hi Denisk, hope you're well (particularly given where you've listed you live)

I'm the person who started the EM Wiki for Jake. Jake is now threatening lawsuits, saying he would assault me if given a chance and is being an all around nasty person. He's got a track record of lying and decieving people https://web.archive.org/web/20230000000000*/cedonulli.com

See these videos I made for more information:
https://www.youtube.com/watch?v=DiSbeWJMK-s
https://www.youtube.com/watch?v=BtRMIsafM1M

I recommend not involving yourself too much more with Endmyopia.

**Comment by denisk20** [comment]
Hello. Really sorry to hear all that, but thanks for letting know... The Diopter Calculator app is not owned by Jake, it's an open source effort hosted in my personal repository (with the ability to be freely copied by anyone). It has Endmyopia in its name and is published on behalf of Endmyopia Google account, but this can be changed easily and might as well be published by anyone else (the source code is under Apache license). Wish you all the best.

**Comment by nottnottloop** [comment]
Hi Denis, good to know, thanks for making an open source tool to help people. 

I hope you are safe given events, praying for success in the counter offensive. Слава Україні!

**Comment by denisk20** [comment]
> Hi Denis, good to know, thanks for making an open source tool to help people.
> 
> I hope you are safe given events, praying for success in the counter offensive. Слава Україні!

Thank you very much! We had to move from our home city of Kharkiv (which is under shelling to this day), to a safer place in central Ukraine. Really appreciate the support of the U.K., you guys are beyond incredible 🙏
